config/routes.rb
Rails.application.routes.draw do
  root "doctors#index"
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users
  resources :doctors do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor

  def index
    @appointments = @doctor.appointments
  end

  def new
    @users = User.all - @doctor.users
    @appointment = @doctor.appointments.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)
    else
      render :new
    end
  end

  def destroy
    @appointment = @doctor.appointments.find(params[:id])
    @appointment.destroy
    redirect_to doctor_appointments_path(@doctor)
  end

  private
  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :time, :user_id)
  end


end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
    redirect_to @doctor
  else
    render :new
  end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = current_user.User.new(user_params)

    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/index.html.erb
<h1><%= @doctor.name %>: Appointments</h1>
<%= link_to 'Add Appointment', 
new_doctor_appointment_path(@doctor) %>
<hr />

<h2> Dates </h2>
<% @appointments.each do |appointment| %>
  <li>
  <%= link_to appointment.date, [@doctor, appointment] %></li>
  <% end %>

<h2> Times </h2>
<% @appointments.each do |appointment| %>
  <li>
  <%= link_to appointment.time, [@doctor, appointment] %></li>
  <% end %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>
<%= form_with(model: [@doctor, @appointment], local: true, class: "ui form" ) do |f| %>
  <br />
  <%= f.label :user %>
  <%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
  <br />
  <%= f.label :date %>
  <%= f.text_field :date, placeholder: "(MM/DD/YY)" %>
  <br />
  <%= f.label :time %>
  <%= f.text_field :time, placeholder: "(H:MM)" %>
  <br />
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
  <% end %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<%= link_to 'Add doctor', new_doctor_path %>
<hr />
<h2><%= @doctors.length <= 0 ? "No doctors" : "" %></h2> 
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/doctors/show.html.erb
<h1> <%= @doctor.name %> </h1>
<hr />
<br />
  <%= link_to "Appointments", doctor_appointments_path(@doctor), class: "ui primary button inverted" %>
<br />
<br />
<br />
  <%= link_to "Delete Doctor", @doctor, method: :delete, class: "ui red button inverted" %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Doctors', doctors_path %>
    </li>
    <li>
      <%= link_to 'Add Doctor', new_doctor_path %>
    </li>
    <li>
      <%= link_to 'Users', users_path %>
    </li>
    <li>
      <%= link_to 'Add User', new_user_path %>
    </li>
    <li>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorAppt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
      <div class="ui container">
        <%= yield %>
      </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'Add User', new_user_path %>
<hr />
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.full_name, user_path(user)%>
    </li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>Add User</h1>
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul>
  <% @user.doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor_path(doctor) %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete User', user_path(@user), method: :delete, class: "ui red button inverted" %>